# Generated by Django 3.0.3 on 2020-03-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mt_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('mt_price', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('dc_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.received_details')),
            ],
        ),
        migrations.AlterField(
            model_name='received_details',
            name='m_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.mt_type'),
        ),
    ]
