# Generated by Django 3.0.3 on 2020-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20200314_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received_details',
            name='m_length',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
