# Generated by Django 3.0.3 on 2020-03-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20200314_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt_type',
            name='mt_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='received_details',
            name='m_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
